config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # SHOW Routes
   get 'customers'     => 'customers#index'

   get 'customers/alphabetized'     => 'customers#alphabetized' , as: 'alphabetized'

   get 'customers/missing_email'     => 'customers#missing_email', as: 'missing_email'



   root to: 'customers#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  
  validates :fullname,:phonenumber,:image,:notes, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:fullname)
  end

  def missing_email
    @customers = Customer.where(:emailaddress => '')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer">
  <p>
    <strong>Full Name:</strong>
    <%= customer.fullname %>
  </p>

  <p>
    <strong>Phone Number:</strong>
    <%= customer.phonenumber %>
  </p>

<% if customer.province_id.to_i() > 0 %>
  <p>
    <strong>Province:</strong>
    <%= customer.province.name %>
  </p>
<% else %>
<p>
  <strong>Province: None</strong>
</p>
<% end %>

 <% if customer.emailaddress != '' %>
  <p>
    <strong>Email Address:</strong>
    <%= customer.emailaddress %>
  </p>
 <% end %>

 <p>
   <strong>Notes:</strong>
   <%= customer.notes %>
 </p>


  <p>
    <%= image_tag customer.image %>
  </p>
</div>

app/views/customers/alphabetized.html.erb
<h2>All Ordered Customers</h2>

<p>
  <%= link_to 'All  Customers', customers_path %>
  - <%= link_to 'Missing Email Customers', missing_email_path %>
</p>

<%= render partial: 'customer', collection: @customers %>

app/views/customers/index.html.erb
<h2>All Customers</h2>

<p>
  <%= link_to 'Alphabetized  Customers', alphabetized_path %>
  - <%= link_to 'Missing Email Customers', missing_email_path %>
</p>

<%= render partial: 'customer', collection: @customers %>

app/views/customers/missing_email.html.erb
<h2>Missing email address</h2>

<p>
  <%= link_to 'All  Customers', customers_path %>
  -<%= link_to 'Alphabetized  Customers', alphabetized_path %>
</p>

<%= render partial: 'customer', collection: @customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>